# Generated by Django 4.1.5 on 2023-03-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_basket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity_buying',
            field=models.FloatField(verbose_name='Общая количество'),
        ),
    ]
