# Generated by Django 4.1.5 on 2023-03-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_quantity_buying_buy_total_buying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity_buying',
            field=models.FloatField(null=True, verbose_name='Общая количество'),
        ),
    ]
