# Generated by Django 4.1.5 on 2023-03-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_basket_quantity_buying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity_buying',
            field=models.FloatField(verbose_name='Общая количество'),
        ),
    ]
