# Generated by Django 4.1.5 on 2023-04-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_basket_quantity_buying'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='url',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
    ]
